/*
 * Copyright (c) 1987-2022 Angband contributors.
 *
 * This work is free software; you can redistribute it and/or modify it
 * under the terms of either:
 *
 * a) the GNU General Public License as published by the Free Software
 *    Foundation, version 2, or
 *
 * b) the Angband licence:
 *    This software may be copied and distributed for educational, research,
 *    and not for profit purposes provided that this copyright and statement
 *    are included in all such copies.  Other copyrights may also apply.
 *
 *    Java code and ANTLR4 grammars copyright (c) Rowan Crowther 2026
 */

package uk.co.jackoftradesltd.frontend.globals;

/**
 * Static holder for the front end's globally-shared UI state, the Java port of the C
 * original's module-scope globals in {@code z-textblock.c} ({@code [C] src/z-textblock.h:57-61})
 * and the file-scoped stat-name table in {@code ui-entry.c} ({@code [C] src/ui-entry.c:1603-1622}).
 * Wraps {@code text_out_indent} and C's five-entry {@code stat_names} abbreviation array; C's
 * neighbouring {@code text_out_wrap} and {@code text_out_pad} globals (and the
 * {@code text_out_hook}/{@code text_out_file} pointers) have no counterpart here yet.
 *
 * <p>Class UIGlobals coded before 260911, commented in full on 260919.
 *
 * @author Rowan Crowther
 */
public class UIGlobals {
    /**
     * The current indentation for wrapped text, the Java port of the C original's
     * {@code text_out_indent} ({@code [C] src/z-textblock.c:382}). Read at the start of each
     * output line by whichever hook writes wrapped text to a file, to pad that line's indent; C
     * default-initialises it to {@code 0}, which this mirrors with an explicit static
     * initializer.
     *
     * <p>Field textOutIndent coded before 260911, commented in full on 260911.
     */
    private static int textOutIndent;

    /**
     * The five player stat abbreviations, the Java port of the C original's file-scoped
     * {@code stat_names} array in {@code ui-entry.c} ({@code [C] src/ui-entry.c:1603-1607}),
     * itself generated by expanding the {@code STAT(x)} macro over {@code list-stats.h}
     * ({@code [C] src/list-stats.h:14-18}). Order matches C exactly: STR, INT, WIS, DEX, CON.
     *
     * <p>Field statNames coded on 260919, commented in full on 260919.
     */
    private static final String[] statNames = {"STR", "INT", "WIS", "DEX", "CON"};

    static {
        textOutIndent = 0;
    }

    /**
     * Returns the abbreviation for the stat at the given index, the Java port of the C
     * original's {@code get_stat_name} ({@code [C] src/ui-entry.c:1617-1622}). C guards the
     * index with an {@code assert} against {@code get_stat_count()}; that count function has no
     * counterpart here yet, so an out-of-range index falls through to Java's own array-bounds
     * check and throws {@link ArrayIndexOutOfBoundsException} instead of failing the assert.
     *
     * <p>Function getStatName coded on 260919, commented in full on 260919.
     *
     * @param index the stat's position in C's {@code list-stats.h} order (0 = STR .. 4 = CON)
     * @return the three-letter stat abbreviation, e.g. {@code "STR"}
     */
    public static String getStatName(int index) {
        return statNames[index];
    }

    /**
     * Returns the current text-output indentation, the Java port of the C original's direct
     * reads of {@code text_out_indent} ({@code [C] src/z-textblock.c:446, 464}).
     *
     * <p>Function getTextOutIndent coded before 260911, commented in full on 260911.
     *
     * @return the number of columns to indent wrapped text by
     */
    public static int getTextOutIndent() {
        return textOutIndent;
    }

    /**
     * Sets the text-output indentation, the Java port of the C original's direct assignments to
     * {@code text_out_indent} ({@code [C] src/z-textblock.c}) made by call sites such as
     * {@code ui-birth.c}, {@code ui-store.c} and {@code ui-target.c} around blocks of
     * {@code text_out} calls, each later resetting it back to {@code 0}.
     *
     * <p>Function setTextOutIndent coded before 260911, commented in full on 260911.
     *
     * @param textOutIndent the number of columns to indent wrapped text by
     */
    public static void setTextOutIndent(int textOutIndent) {
        UIGlobals.textOutIndent = textOutIndent;
    }
}
