/*
 * Copyright (c) 1987-2022 Angband contributors.
 *
 * This work is free software; you can redistribute it and/or modify it
 * under the terms of either:
 *
 * a) the GNU General Public License as published by the Free Software
 *    Foundation, version 2, or
 *
 * b) the Angband licence:
 *    This software may be copied and distributed for educational, research,
 *    and not for profit purposes provided that this copyright and statement
 *    are included in all such copies.  Other copyrights may also apply.
 *
 *    Java code and ANTLR4 grammars copyright (c) Rowan Crowther 2026
 */

package uk.co.jackoftrades.backend.parser;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.misc.ParseCancellationException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.jetbrains.annotations.CheckReturnValue;
import org.jetbrains.annotations.Contract;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Class to collect the errors occurring during the parsing of game data files
 * and store them to throw them in one list at the end.
 *
 * @author Rowan Crowther
 */
public final class ParseErrors extends BaseErrorListener {
    /**
     * Logger - used to create the log files for this class
     */
    private static final Logger logger = LogManager.getLogger();

    /**
     * List to save the error strings in
     */
    private final List<String> errors = new ArrayList<>();

    /**
     * The name of the file we are parsing
     */
    private final String sourceName;

    /**
     * Private constructor - to force construction through the install
     * method
     *
     * @param sourceName The name of the file we are parsing
     * @author Rowan Crowther
     */
    private ParseErrors(String sourceName) {
        this.sourceName = sourceName;
    }

    /**
     * Installs this ParseErrors class on a given lexer and parser
     *
     * @param lexer    The ANTLR4 lexer we are checking for errors on
     * @param parser   The ANTLR4 parser we are checking for errors on
     * @param filename The filename of the file we are lexing/parsing
     * @return The ParseErrors class set up for this lexer/parser combination
     * parsing filename
     * @author Rowan Crowther
     */
    public static ParseErrors install(Lexer lexer, Parser parser, String filename) {
        ParseErrors collector = new ParseErrors(filename);

        parser.removeErrorListeners();
        lexer.removeErrorListeners();

        parser.addErrorListener(collector);
        lexer.addErrorListener(collector);

        return collector;
    }

    /**
     * @param recognizer         What parser got the error. From this
     *                           object, you can access the context as well
     *                           as the input stream.
     * @param offendingSymbol    The offending token in the input token
     *                           stream, unless recognizer is a lexer (then it's null). If
     *                           no viable alternative error, {@code e} has token at which we
     *                           started production for the decision.
     * @param line               The line number in the input where the error occurred.
     * @param charPositionInLine The character position within that line where the error occurred.
     * @param msg                The message to emit.
     * @param e                  The exception generated by the parser that led to
     *                           the reporting of an error. It is null in the case where
     *                           the parser was able to recover in line without exiting the
     *                           surrounding rule.
     *                           ---
     *                           Overridden to add an error to the error list and then return without
     *                           throwing it.
     * @author Rowan Crowther
     */
    @Override
    public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line, int charPositionInLine, String msg, RecognitionException e) {
        errors.add("file: " + sourceName + " line " + line + ":" + charPositionInLine + " " + msg);
    }

    /**
     * Final method - if no errors have been collected returns otherwise uses the logger
     * to throw them all
     *
     * @author Rowan Crowther
     */
    public void throwIfAny() {
        if (errors.isEmpty())
            return;

        for (String error : errors) {
            logger.error(error);
        }

        throw new ParseCancellationException("Errors occurred during parsing, check Error logfile for details.");
    }

    /**
     * Add in a new error outside the syntaxError route
     *
     * @param line the line number of the file being parsed where the error occured
     * @param msg  the error message
     * @author Rowan Crowther
     */
    public void add(int line, String msg) {
        errors.add("file: " + sourceName + " line " + line + " " + msg);
    }

    /**
     * Add in a new file error outside the syntaxError route
     *
     * @param msg the error message
     * @author Rowan Crowther
     */
    public void add(String msg) {
        errors.add("file: " + sourceName + " " + msg);
    }

    /**
     * Determine whether any errors have been collected by this listener
     *
     * @return true if an error has been caught and is in the queue, false
     * otherwise
     * @author Rowan Crowther
     */
    @CheckReturnValue
    @Contract(pure = true)
    public boolean hasErrors() {
        return !errors.isEmpty();
    }

    /**
     * Return the current list of errors for external examination
     *
     * @return the current list of errors
     * @author Rowan Crowther
     */
    @CheckReturnValue
    @Contract(pure = true)
    public List<String> getErrors() {
        return Collections.unmodifiableList(errors);
    }
}