package uk.co.jackoftrades.background.utils;

import org.jetbrains.annotations.CheckReturnValue;
import org.jetbrains.annotations.Contract;
import org.jspecify.annotations.NonNull;
import uk.co.jackoftrades.background.io.imports.Constant;
import uk.co.jackoftrades.background.utils.globalvalues.DungeonGeneration;
import uk.co.jackoftrades.background.utils.globalvalues.LevelMax;
import uk.co.jackoftrades.background.utils.globalvalues.MonsterGameplay;
import uk.co.jackoftrades.background.utils.globalvalues.MonsterGeneration;

import java.util.ArrayList;

public class GlobalUtils {
    /**
     * The deepest level the dungeon can reach. Used in object and monster creations. Must be greater than 100. Setting
     * less that 128 may prevent some objects being created
     */
    public final static int maxRandDepth = 128;

    /**
     * private constructor to ensure that there is no access to this class apart from by its static methods
     */
    @Contract(pure = true)
    private GlobalUtils() {
    }

    @Contract(pure = true)
    public static void setConstantsValue(@NonNull ArrayList<Constant> constants) {
        for (Constant constant : constants) {
            String section = constant.getSection();
            String value = constant.getValue();

            switch (section) {
                case "level-max":
                    LevelMax.setValue(value);
                    return;

                case "mon-gen":
                    MonsterGeneration.setValue(value);
                    return;

                case "mon-play":
                    MonsterGameplay.setValue(value);
                    return;

                case "dun-gen":
                    DungeonGeneration.setValue(value);
                    return;
            }
        }
    }

    // Getters for global values

    /*
     * Level maximums
     */

    /**
     * Get the maximum number of monsters per level
     *
     * @return The maximum number of monsters per level
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getLevelMonsterMax() {
        return LevelMax.getMaxMonstersPerLevel();
    }

    /*
     * Monster Generation
     */

    /**
     * Get the 1/per-turn-chance of generation of a monster
     *
     * @return the 1/per-turn-chance of generation of a monster
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getAllocMonsterChance() {
        return MonsterGeneration.getAllocMonsterChance();
    }

    /**
     * Gets the minimum number of monsters generated. If this is less than 0 or greater than the maximum number of
     * monsters on a level, an exception is thrown
     *
     * @return the minimum number of monsters generated per level
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getLevelMonsterMin() {
        return MonsterGeneration.getLevelMonsterMin();
    }

    /**
     * Gets the number of townsfolk generated in the town
     *
     * @return the number of townsfolk generated in the town
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getTowMonstersDay() {
        return MonsterGeneration.getTownMonstersDay();
    }

    /**
     * Gets the number of townsfolk generated in the town at night
     *
     * @return the number of townsfolk generated in the town at night
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getTownMonstersNight() {
        return MonsterGeneration.getTownMonstersNight();
    }

    /**
     * Gets the maximum number of breeding monsters (breeders) on a level at any one time
     *
     * @return the maximum number of breeders
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getReproMonsterMax() {
        return MonsterGeneration.getReproMax();
    }

    /**
     * Get the chance of a monsters level being inflated by 1-in-value
     *
     * @return the chance of a monsters level being inflated by 1-in-value
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getOodMonsterChance() {
        return MonsterGeneration.getOodChance();
    }

    /**
     * Gets the amount that an out-of-depth monster can be generated by
     *
     * @return the amount that an out-of-depth monster can be generated by
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getOodMonsterAmount() {
        return MonsterGeneration.getOodAmount();
    }

    /**
     * Gets the maximum number of monsters in a group
     *
     * @return the maximum number of monsters in a group
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getMonsterGroupMax() {
        return MonsterGeneration.getGroupMax();
    }

    /**
     * Gets the maximum distance from one group to that of a related group
     *
     * @return the maximum distance from one group to that of a related group
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getMonsterGroupDist() {
        return MonsterGeneration.getGroupDist();
    }

    /*
     * Monster gameplay constants
     */

    /**
     * HOw hard it is to break a glyph
     *
     * @return Rune of protection resistance to monster breaking
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getGlyphHardness() {
        return MonsterGameplay.getGlyphHardness();
    }

    /**
     * Monster reproduction rate-slower. Higher values slows multiplication
     *
     * @return Monster reproduction rate-slower
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getReproMonsterRate() {
        return MonsterGameplay.getReproMonsterRate();
    }

    /**
     * The percentage of a players experience drained per hit
     *
     * @return the percentage of a players experience drained per hit
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getLifeDrainPercent() {
        return MonsterGameplay.getLifeDrainPercent();
    }

    /**
     * Monsters will run up to this many grids out of site
     *
     * @return The number of grids that terrified monsters will run once out of sight of the player
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getFleeRange() {
        return MonsterGameplay.getFleeRange();
    }

    /**
     * Terrified monsters will turn to fight if they are slower than the player and closer than this distance.
     *
     * @return The distance at which a monster will turn to fight if they are slower than the player and terrified.
     */
    @CheckReturnValue
    @Contract(pure = true)
    public static int getTurnRange() {
        return MonsterGameplay.getTurnRange();
    }

    /*
     * Dungeon generation constants
     */

    /**
     * Get the maximum number of fooms on a level
     *
     * @return the maximum number of fooms on a level
     */
    @Contract(pure = true)
    public static int getLevelRoomMax() {
        return DungeonGeneration.getCentMax();
    }

    /**
     * Get the maximum potential number of door locations
     *
     * @return the maximum potential number of door locations
     */
    @Contract(pure = true)
    public static int getLevelDoorMax() {
        return DungeonGeneration.getDoorMax();
    }

    /**
     * Get the maximum potential number of wall locations that can be pierced
     *
     * @return the maximum potential number of wall locations that can be pierced
     */
    @Contract(pure = true)
    public static int getWallPierceMax() {
        return DungeonGeneration.getWallMax();
    }

    /**
     * Get the maximum number of tunnel grids
     *
     * @return the maximum number of tunnel grids
     */
    @Contract(pure = true)
    public static int getTunnGridMax() {
        return DungeonGeneration.getTunnMax();
    }

    /**
     * Get the average number of items in a room
     *
     * @return the average number of items in a room
     */
    @Contract(pure = true)
    public static int getRoomItemAv() {
        return DungeonGeneration.getAmtRoom();
    }

    /**
     * Get the average number of objects placed in random locations
     *
     * @return the average number of objects placed in random locations
     */
    @Contract(pure = true)
    public static int getBothItemAv() {
        return DungeonGeneration.getAmtItems();
    }

    /**
     * Get the average number of treasure/money items in random places
     *
     * @return the average number of treasure/money items in random places
     */
    @Contract(pure = true)
    public static int getBothGoldAv() {
        return DungeonGeneration.getAmtGold();
    }

    /**
     * Get the maximum number of pits/nests allowed on a level
     *
     * @return the maximum number of pits/nests allowed on a level
     */
    @Contract(pure = true)
    public static int getLevelPitMax() {
        return DungeonGeneration.getPitMax();
    }
}